name: Zagware IaC Scanner

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: zagware-iac-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  iac-scan:
    name: IaC security scan
    runs-on: ubuntu-latest
    steps:
      - name: Zagware IaC Scanner
        uses: docker://davymcaleer99/zagware-iac-scan:latest
        env:
          GITHUB_TOKEN:            ${{ github.token }}
          PR_NUMBER:               ${{ github.event.pull_request.number }}
          ZAGWARE_PLATFORM_URL:    https://app.zagware.io
          ZAGWARE_PLATFORM_TOKEN:  ${{ secrets.GTP_API_TOKEN }}
